WaveSpecs = struct( ...
  'Name', {'default'}, ...
  'RawRate', {1e6}, ...
  'RawSamples', {1000}, ...
  'NetSamples', {1000}, ...
  'NAverage', {1}, ...
  'NCoadd', {1}, ...
  'FTrigger', {1000}, ...
  'ISICOS', {1}, ...
  'TzSamples', {30}, ...
  'dIdt', {0}, ...
  'I0', {0} ...
);
